# Explore, Visualize, and Predict using Pandas & Jupyter

### Learn to import, explore, and tweak your data

Matt Harrison (@\_\_mharrison\_\_)

The pandas library is very popular among data scientists, quants, Excel junkies, and Python developers because it allows you to perform data ingestion, exporting, transformation, and visualization with ease. But if you are only familiar with Python, pandas may present some challenges. Since pandas is inspired by Numpy, its syntax conventions can be confusing to Python developers.

If you have questions on Python syntax, check out https://github.com/mattharrison/Tiny-Python-3.6-Notebook

Much of this content is based on my Pandas book, [*Learning the Pandas Library*](https://www.amazon.com/Learning-Pandas-Library-Munging-Analysis/dp/153359824X/ref=sr_1_3?ie=UTF8&qid=1505448275&sr=8-3&keywords=python+pandas)

# Jupyter Intro

Jupyter notebook is an environment for combining interactive coding and text in a webbrowser. This allows us to easily share code as well as narrative around that code. An example that was popular in the scientific community was [the discovery of gravitational waves.](https://losc.ligo.org/s/events/GW150914/GW150914_tutorial.html)

The name Jupyter is a rebranding of an open source project previously known as iPython Notebook. The rebranding was to emphasize that although the backend is written in Python, it supports various *kernals* to run other languages, including Julia (the "Ju" portion), Python ("pyt"), and R ("er"). All popular *data science* programming languages.

The architecture of Jupyter includes a server running various kernals. Using a *notebook* we can interact with a kernal. Typically we use a webbrowser to do this, but there are other iterfaces, such as an emacs mode (ein).

## Using Jupyter

After we create a notebook, we are presented with a page with an empty cell. The cell will have a blue outline, ane the text:

    In [ ]: 
    
on the side. The blue outline indicates that we are in *command mode*. There are two modes in Jupyter, command mode and *edit mode*.

To enter edit mode simply hit the enter or return key. You will notice that the outline will change to green. In edit mode, with a Python kernel, we can type Python code. Type:

    print("hello world")
    
You will notice that unlike a normal Python REPL, this will note print anything after hitting return again. To *execute* the cell, you need to hold down control and hit enter (``C-Enter``). This will run the code, print the results of the cell and put you back into edit mode.     

## Edit Mode

To enter *Edit Mode* you need to click on a cell or hit enter when it is surrounded by the blue outline. You will see that it goes green if you are in edit mode. In edit mode you have basic editing functionality. A few keys to know:

* Ctr-Enter - Run cell (execute Python code, render Markdown)
* ESC - Go back to command mode
* TAB - Tab completion
* Shift-TAB - Bring up tooltip (ESC to dismiss)


## Command Mode

*Command Mode* gives to the ability to create, copy, paste, move, and execute cells. A few keys to know:

* h - Bring up help (ESC to dismiss)
* b - Create cell below
* a - Create cell above
* c - Copy cell
* v - Paste cell below
* Enter - Go into Edit Mode
* m - Change cell type to Markdown
* y - Change cell type to code
* ii - Interrupt kernel
* oo - Restart kernel

## Cell Types

* Code
* Markdown


## Markdown

Can make *italicized*, **bold**, and ``monospaced text``:

    Can make *italicized*, **bold**, and ``monospaced text``


Headers:

    # H1
    ## H2
    ### H3
 
Lists:

    * First item
    * Second item
    
Code:

    If you indent by four spaces you have code:
    
        def add(x, y):
            return x + yt
    
## Cell Magic

type and run ``%lsmagic`` in a cell.

Common magics include:

* ``%%time`` - time how long it takes to run cell
* ``%%!`` - run shell command
* ``%matplotlib inline`` - show matplotlib plots


## IPython Help
Add ? after function, method, etc for documentation (can also run shift-tab 4 times in notebook). Add ?? after function, method, etc to see the source.

# Setup

In [1]:
import pandas as pd
import matplotlib
import numpy as np

pd.__version__, matplotlib.__version__, np.__version__

('0.20.3', '2.0.2', '1.13.3')

In [2]:
# test for unicode
'\N{SNAKE}'

'üêç'

In [3]:
import sys
sys.getdefaultencoding()

'utf-8'

In [4]:
sys.version

'3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) \n[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]'

# Pandas Intro

## Installation

Presumably, you have pandas installed if you ran the cell after **Setup** successfully. The Anaconda distribution is a common way to get the Python scientific stack up and running quickly on most platforms. Running ``pip install pandas`` works as well.

In [5]:
# pandas has two main datatypes: a Series and a DataFrame
# A Series is like a column from a spreadsheet

s = pd.Series([0, 4, 6, 7])

In [6]:
# A DataFrame is like a spreadsheet

df = pd.DataFrame({'name': ['Fred', 'Johh', 'Joe', 'Abe'], 'age': s})

In [7]:
# We can do tab completion on objects that exist (shift tab brings up tooltip)
# ?? brings up source
pd.Series??

In [8]:
s

0    0
1    4
2    6
3    7
dtype: int64

The first Column is an index the second column is actually a the data. 
As you can see the dtype is int64 and it is using the C interpreter type. 
Undercover pandas uses the Cython to speed up the implementation without care about C.
Thsi is the dirty trick.

In [9]:
df

   age  name
0    0  Fred
1    4  Johh
2    6   Joe
3    7   Abe

When you use the df you can see a nice notation in html.

In [10]:
len(dir(s))

439

In [11]:
len(dir(s))

439

In [12]:
len(dir(df))

447

In [13]:
len(set(dir(s))& set(dir(df)))

377

As you can see most of the attributes are common to both data structures. By the way the dir function enumerates the attributes of an object.

# Datasets

For this class we will look at some time series data. The class will look at Central Park weather. The assignments will deal with El Nino data.

## Central Park


https://pastebin.com/vaB6QQGp

## El Nino

https://archive.ics.uci.edu/ml/datasets/El+Nino

In [14]:
%matplotlib inline
# I typically start with imports like this including the matplotlib magic 
# for most notebooks
import pandas as pd
import numpy as np

# Getting Data
There are various ``pd.read_`` functions for ingesting data

In [15]:
# not necessary if you started jupyter from the project directory
%ls data/
# should have central-park-raw.csv

central-park-raw.csv  tao-all2.dat.gz       vehicles.csv.zip

In [16]:
# if you execute this cell it will bring up a tooltip due to
# the ? at the end. You can also hit shift-tab 4 times
# if your cursor is after the v
# Hit escape to dismiss the tooltip
pd.read_csv?

As you can see the signature is very complex. The reason behind is the signature covers all the csv files that you can think of.

In [17]:
# let's load the data and treat column 0 as a date
nyc = pd.read_csv('data/central-park-raw.csv', parse_dates=[0])
# Jupyter will print the result of the last command
nyc

,EST,Max TemperatureF,Mean TemperatureF,Min TemperatureF,Max Dew PointF,MeanDew PointF,Min DewpointF,Max Humidity,Mean Humidity,Min Humidity,...,Max VisibilityMiles,Mean VisibilityMiles,Min VisibilityMiles,Max Wind SpeedMPH,Mean Wind SpeedMPH,Max Gust SpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,2006-01-01,42.0,37.0,32.0,32.0,30.0,28.0,85.0,74.0,62.0,...,10.0,10.0,8.0,9.0,3.0,10.0,0.00,8.0,NaN,276.0
1,2006-01-02,48.0,44.0,39.0,38.0,34.0,29.0,92.0,71.0,49.0,...,10.0,8.0,4.0,18.0,5.0,24.0,0.63,5.0,Rain,76.0
2,2006-01-03,40.0,37.0,33.0,38.0,33.0,26.0,92.0,84.0,75.0,...,10.0,7.0,2.0,28.0,15.0,41.0,1.13,8.0,Rain,39.0
3,2006-01-04,38.0,34.0,29.0,36.0,26.0,19.0,85.0,72.0,59.0,...,10.0,10.0,4.0,15.0,7.0,20.0,0.00,3.0,NaN,70.0
4,2006-01-05,50.0,44.0,37.0,38.0,35.0,32.0,92.0,71.0,50.0,...,10.0,6.0,2.0,15.0,5.0,21.0,0.05,6.0,Rain,251.0
5,2006-01-06,43.0,37.0,30.0,33.0,24.0,14.0,73.0,60.0,47.0,...,10.0,10.0,10.0,17.0,6.0,25.0,0.00,7.0,NaN,317.0
6,2006-01-07,35.0,30.0,25.0,19.0,14.0,11.0,60.0,51.0,41.0,...,10.0,10.0,10.0,15.0,7.0,23.0,0.00,2.0,NaN,267.0
7,2006-01-08,46.0,40.0,34.0,35.0,25.0,19.0,70.0,56.0,41.0,...,10.0,10.0,10.0,13.0,5.0,17.0,0.00,3.0,NaN,192.0
8,2006-01-09,60.0,52.0,43.0,39.0,36.0,30.0,76.0,60.0,44.0,...,10.0,10.0,10.0,15.0,8.0,24.0,0.00,1.0,NaN,249.0
9,2006-01-10,49.0,45.0,41.0,31.0,28.0,26.0,62.0,52.0,42.0,...,10.0,10.0,10.0,10.0,6.0,16.0,0.00,1.0,NaN,261.0
10,2006-01-11,52.0,47.0,42.0,50.0,42.0,30.0,96.0,79.0,62.0,...,10.0,4.0,1.0,14.0,4.0,21.0,0.23,7.0,Rain,71.0
11,2006-01-12,57.0,51.0,45.0,45.0,36.0,31.0,89.0,63.0,36.0,...,10.0,10.0,10.0,15.0,7.0,20.0,0.00,0.0,NaN,246.0
12,2006-01-13,54.0,49.0,43.0,52.0,43.0,39.0,96.0,81.0,66.0,...,10.0,4.0,1.0,12.0,3.0,17.0,0.00,5.0,NaN,171.0
13,2006-01-14,57.0,44.0,31.0,55.0,49.0,26.0,100.0,91.0,82.0,...,10.0,5.0,1.0,18.0,9.0,36.0,1.17,8.0,Rain,158.0
14,2006-01-15,32.0,24.0,16.0,25.0,12.0,-1.0,92.0,62.0,32.0,...,10.0,6.0,0.0,31.0,13.0,39.0,0.12,5.0,Fog-Snow,298.0
15,2006-01-16,32.0,24.0,16.0,9.0,5.0,1.0,54.0,44.0,33.0,...,10.0,10.0,10.0,16.0,8.0,24.0,0.00,0.0,NaN,279.0
16,2006-01-17,44.0,35.0,26.0,39.0,21.0,8.0,82.0,59.0,35.0,...,10.0,9.0,2.0,14.0,6.0,20.0,0.16,5.0,Rain,67.0
17,2006-01-18,58.0,47.0,36.0,55.0,43.0,19.0,93.0,69.0,44.0,...,10.0,6.0,2.0,28.0,12.0,41.0,0.59,7.0,Rain,217.0
18,2006-01-19,47.0,41.0,34.0,27.0,21.0,18.0,56.0,47.0,37.0,...,10.0,10.0,10.0,17.0,8.0,23.0,0.00,0.0,NaN,244.0
19,2006-01-20,61.0,52.0,42.0,36.0,32.0,28.0,62.0,49.0,36.0,...,10.0,10.0,10.0,16.0,8.0,23.0,0.00,0.0,NaN,233.0
20,2006-01-21,63.0,51.0,38.0,42.0,32.0,18.0,61.0,53.0,44.0,...,10.0,10.0,10.0,26.0,10.0,39.0,0.00,2.0,NaN,263.0
21,2006-01-22,43.0,38.0,33.0,26.0,16.0,11.0,52.0,40.0,27.0,...,10.0,10.0,10.0,15.0,7.0,23.0,0.00,1.0,NaN,49.0
22,2006-01-23,40.0,38.0,35.0,38.0,35.0,28.0,92.0,76.0,59.0,...,10.0,7.0,2.0,14.0,4.0,17.0,0.68,7.0,Rain-Snow,51.0
23,2006-01-24,46.0,41.0,35.0,30.0,26.0,15.0,76.0,54.0,31.0,...,10.0,10.0,10.0,14.0,7.0,18.0,0.00,1.0,NaN,185.0
24,2006-01-25,42.0,38.0,34.0,32.0,26.0,18.0,82.0,65.0,47.0,...,10.0,10.0,10.0,22.0,10.0,32.0,0.00,4.0,NaN,266.0
25,2006-01-26,35.0,31.0,26.0,19.0,14.0,10.0,56.0,47.0,38.0,...,10.0,10.0,10.0,21.0,14.0,30.0,0.00,1.0,NaN,292.0
26,2006-01-27,43.0,34.0,24.0,15.0,10.0,4.0,60.0,40.0,19.0,...,10.0,10.0,10.0,16.0,8.0,22.0,0.00,0.0,NaN,274.0
27,2006-01-28,58.0,48.0,37.0,27.0,20.0,14.0,40.0,33.0,26.0,...,10.0,10.0,10.0,13.0,6.0,21.0,0.00,0.0,NaN,243.0
28,2006-01-29,53.0,49.0,44.0,49.0,39.0,26.0,93.0,66.0,38.0,...,10.0,8.0,2.0,13.0,5.0,20.0,0.14,5.0,Rain,169.0
29,2006-01-30,64.0,53.0,41.0,48.0,43.0,39.0,96.0,70.0,43.0,...,10.0,6.0,2.0,20.0,8.0,28.0,0.01,4.0,NaN,64.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3257,2014-12-02,43.0,39.0,35.0,40.0,30.0,17.0,89.0,67.0,44.0,...,10.0,8.0,2.0,17.0,9.0,26.0,0.08,7.0,Rain,70.0
3258,2014-12-03,46.0,44.0,41.0,43.0,38.0,24.0,92.0,73.0,53.0,...,10.0,6.0,2.0,16.0,8.0,26.0,0.06,7.0,Rain,276.0
3259,2014-12-04,45.0,41.0,37.0,24.0,21.0,17.0,59.0,48.0,36.0,...,10.0,10.0,10.0,13.0,6.0,19.0,0.00,0.0,NaN,304.0
3260,2014-12-05,44.0,39.0,34.0,41.0,33.0,19.0,89.0,69.0,48.0,...,10.0,6.0,1.0,17.0,6.0,21.0,0.51,6.0,Rain,50.0
3261,2014-12-06,50.0,45.0,39.0,47.0,42.0,36.0,96.0,88.0,80.0,...,8.0,3.0,1.0,17.0,4.0,30.0,1.22,8.0,Rain,36.0
3262,2014-12-07,42.0,36.0,30.0,35.0,18.0,0.0,92.0,62.0,32.0,...,10.0,10.0,10.0,25.0,12.0,40.0,0.04,1.0,Rain,28.0
3263,2014-12-08,37.0,31.0,24.0,30.0,17.0,-1.0,75.0,51.0,27.0,...,10.0,10.0,10.0,20.0,12.0,29.0,0.00,6.0,NaN,60.0
3264,2014-12-09,42.0,39.0,36.0,38.0,36.0,30.0,92.0,81.0,70.0,...,10.0,5.0,1.0,22.0,10.0,32.0,2.54,8.0,Rain,36.0
3265,2014-12-10,40.0,36.0,32.0,36.0,31.0,23.0,89.0,74.0,59.0,...,10.0,6.0,1.0,16.0,8.0,24.0,0.08,8.0,Rain-Snow,295.0
3266,2014-12-11,38.0,35.0,31.0,26.0,23.0,20.0,75.0,62.0,48.0,...,10.0,9.0,2.0,17.0,8.0,25.0,0.01,7.0,Snow,276.0
3267,2014-12-12,38.0,35.0,32.0,23.0,21.0,19.0,61.0,57.0,52.0,...,10.0,10.0,10.0,15.0,8.0,25.0,0.00,6.0,NaN,303.0
3268,2014-12-13,44.0,39.0,34.0,28.0,25.0,21.0,64.0,54.0,43.0,...,10.0,10.0,10.0,16.0,9.0,28.0,0.00,2.0,NaN,307.0
3269,2014-12-14,46.0,42.0,38.0,29.0,29.0,28.0,70.0,60.0,49.0,...,10.0,10.0,10.0,13.0,6.0,20.0,0.00,4.0,NaN,306.0
3270,2014-12-15,48.0,43.0,37.0,34.0,29.0,28.0,70.0,58.0,46.0,...,10.0,10.0,10.0,8.0,3.0,12.0,0.00,0.0,NaN,333.0
3271,2014-12-16,49.0,44.0,38.0,43.0,39.0,32.0,86.0,76.0,65.0,...,10.0,6.0,2.0,12.0,4.0,14.0,0.20,7.0,Rain,75.0
3272,2014-12-17,54.0,48.0,42.0,43.0,39.0,26.0,92.0,73.0,53.0,...,10.0,7.0,2.0,16.0,6.0,26.0,0.02,7.0,Rain,294.0
3273,2014-12-18,42.0,40.0,37.0,25.0,23.0,21.0,59.0,52.0,45.0,...,10.0,10.0,10.0,16.0,9.0,28.0,0.00,6.0,NaN,293.0
3274,2014-12-19,38.0,35.0,31.0,25.0,21.0,19.0,63.0,56.0,48.0,...,10.0,10.0,10.0,14.0,7.0,24.0,0.00,5.0,NaN,307.0
3275,2014-12-20,33.0,32.0,30.0,21.0,19.0,18.0,63.0,57.0,51.0,...,10.0,10.0,10.0,12.0,5.0,15.0,0.00,8.0,NaN,10.0
3276,2014-12-21,36.0,34.0,31.0,29.0,25.0,21.0,82.0,73.0,63.0,...,10.0,9.0,6.0,9.0,5.0,13.0,T,8.0,Snow,338.0
3277,2014-12-22,44.0,40.0,35.0,42.0,35.0,29.0,89.0,82.0,75.0,...,10.0,8.0,5.0,12.0,6.0,16.0,0.04,8.0,Rain,59.0
3278,2014-12-23,46.0,45.0,43.0,44.0,42.0,41.0,96.0,91.0,86.0,...,9.0,3.0,2.0,17.0,8.0,26.0,0.16,8.0,Rain,67.0
3279,2014-12-24,58.0,51.0,44.0,57.0,47.0,43.0,100.0,96.0,92.0,...,7.0,3.0,1.0,12.0,6.0,17.0,0.80,8.0,Rain,86.0
3280,2014-12-25,62.0,53.0,44.0,60.0,40.0,27.0,100.0,69.0,38.0,...,10.0,8.0,2.0,20.0,10.0,32.0,0.09,5.0,Rain,279.0
3281,2014-12-26,50.0,45.0,40.0,29.0,28.0,27.0,64.0,53.0,42.0,...,10.0,10.0,10.0,13.0,6.0,18.0,0.00,0.0,NaN,272.0
3282,2014-12-27,55.0,50.0,44.0,35.0,31.0,29.0,53.0,47.0,41.0,...,10.0,10.0,10.0,14.0,4.0,25.0,0.00,0.0,NaN,257.0
3283,2014-12-28,54.0,49.0,43.0,43.0,37.0,26.0,92.0,73.0,53.0,...,10.0,9.0,2.0,15.0,6.0,22.0,0.10,5.0,Rain,264.0
3284,2014-12-29,44.0,39.0,34.0,25.0,19.0,15.0,53.0,42.0,31.0,...,10.0,10.0,10.0,15.0,5.0,25.0,0.00,0.0,NaN,308.0
3285,2014-12-30,34.0,31.0,28.0,17.0,13.0,8.0,58.0,47.0,36.0,...,10.0,10.0,10.0,10.0,4.0,17.0,0.00,2.0,NaN,5.0
3286,2014-12-31,32.0,30.0,27.0,12.0,8.0,5.0,55.0,43.0,30.0,...,10.0,10.0,10.0,14.0,6.0,21.0,0.00,2.0,NaN,275.0

In [18]:
# dataframes can get big, so only show the first bit
nyc.head()

,EST,Max TemperatureF,Mean TemperatureF,Min TemperatureF,Max Dew PointF,MeanDew PointF,Min DewpointF,Max Humidity,Mean Humidity,Min Humidity,...,Max VisibilityMiles,Mean VisibilityMiles,Min VisibilityMiles,Max Wind SpeedMPH,Mean Wind SpeedMPH,Max Gust SpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,2006-01-01,42.0,37.0,32.0,32.0,30.0,28.0,85.0,74.0,62.0,...,10.0,10.0,8.0,9.0,3.0,10.0,0.00,8.0,NaN,276.0
1,2006-01-02,48.0,44.0,39.0,38.0,34.0,29.0,92.0,71.0,49.0,...,10.0,8.0,4.0,18.0,5.0,24.0,0.63,5.0,Rain,76.0
2,2006-01-03,40.0,37.0,33.0,38.0,33.0,26.0,92.0,84.0,75.0,...,10.0,7.0,2.0,28.0,15.0,41.0,1.13,8.0,Rain,39.0
3,2006-01-04,38.0,34.0,29.0,36.0,26.0,19.0,85.0,72.0,59.0,...,10.0,10.0,4.0,15.0,7.0,20.0,0.00,3.0,NaN,70.0
4,2006-01-05,50.0,44.0,37.0,38.0,35.0,32.0,92.0,71.0,50.0,...,10.0,6.0,2.0,15.0,5.0,21.0,0.05,6.0,Rain,251.0

## Getting Data Assignment

For your assignment, you will look at El Nino data.

The [website](https://archive.ics.uci.edu/ml/datasets/El+Nino)  states:

    The data is stored in an ASCII files with one observation per line. Spaces separate fields and periods (.) denote missing values.


Load the ``data/tao-all2.dat.gz`` file into a data frame using ``pd.read_csv``.
Use the ``names`` variable for the initial column names (taken from website).
Replace empty values (``.``) with ``NaN``. Pull the year, month, and date columns into a single variable using the ``parse_dates`` parameter (see the ``pd.read_csv`` docs for info on this).

In [19]:
# date, latitude, longitude, zonal winds (west<0, east>0), meridional winds (south<0, north>0), relative humidity, air temperature, sea surface temperature and subsurface temperatures down to a depth of 500 meters.
names=[ 
    'obs',
    'year',
    'month',
    'day',
    'date',
    'latitude',
    'longitude',
    'zon.winds',
    'mer.winds',
    'humidity',
    'air temp.',
    's.s.temp.']

nino= pd.read_csv('data/tao-all2.dat.gz',sep=' ', names=names,na_values='.',parse_dates=['date'])

In [20]:
nino.head()

,obs,year,month,day,date,latitude,longitude,zon.winds,mer.winds,humidity,air temp.,s.s.temp.
0,1,80,3,7,1980-03-07,-0.02,-109.46,-6.8,0.7,NaN,26.14,26.24
1,2,80,3,8,1980-03-08,-0.02,-109.46,-4.9,1.1,NaN,25.66,25.97
2,3,80,3,9,1980-03-09,-0.02,-109.46,-4.5,2.2,NaN,25.69,25.28
3,4,80,3,10,1980-03-10,-0.02,-109.46,-3.8,1.9,NaN,25.57,24.31
4,5,80,3,11,1980-03-11,-0.02,-109.46,-4.2,1.5,NaN,25.30,23.19

# Inspecting Data

In [21]:
# Interesting aside, the columns are actually an Index 
nyc.columns

Index(['EST', 'Max TemperatureF', 'Mean TemperatureF', 'Min TemperatureF',
       'Max Dew PointF', 'MeanDew PointF', 'Min DewpointF', 'Max Humidity',
       ' Mean Humidity', ' Min Humidity', ' Max Sea Level PressureIn',
       ' Mean Sea Level PressureIn', ' Min Sea Level PressureIn',
       ' Max VisibilityMiles', ' Mean VisibilityMiles', ' Min VisibilityMiles',
       ' Max Wind SpeedMPH', ' Mean Wind SpeedMPH', ' Max Gust SpeedMPH',
       'PrecipitationIn', ' CloudCover', ' Events', ' WindDirDegrees'],
      dtype='object')

In [23]:
# If is good to know if columns have a [correct] type, (object could mean string)
nyc.dtypes

EST                           datetime64[ns]
Max TemperatureF                     float64
Mean TemperatureF                    float64
Min TemperatureF                     float64
Max Dew PointF                       float64
MeanDew PointF                       float64
Min DewpointF                        float64
Max Humidity                         float64
 Mean Humidity                       float64
 Min Humidity                        float64
 Max Sea Level PressureIn            float64
 Mean Sea Level PressureIn           float64
 Min Sea Level PressureIn            float64
 Max VisibilityMiles                 float64
 Mean VisibilityMiles                float64
 Min VisibilityMiles                 float64
 Max Wind SpeedMPH                   float64
 Mean Wind SpeedMPH                  float64
 Max Gust SpeedMPH                   float64
PrecipitationIn                       object
 CloudCover                          float64
 Events                               object
 WindDirDegrees                      float64
dtype: object

In [24]:
# we can also see how much space is taken up
nyc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3287 entries, 0 to 3286
Data columns (total 23 columns):
EST                           3287 non-null datetime64[ns]
Max TemperatureF              3285 non-null float64
Mean TemperatureF             3285 non-null float64
Min TemperatureF              3285 non-null float64
Max Dew PointF                3285 non-null float64
MeanDew PointF                3285 non-null float64
Min DewpointF                 3285 non-null float64
Max Humidity                  3285 non-null float64
 Mean Humidity                3285 non-null float64
 Min Humidity                 3285 non-null float64
 Max Sea Level PressureIn     3275 non-null float64
 Mean Sea Level PressureIn    3275 non-null float64
 Min Sea Level PressureIn     3275 non-null float64
 Max VisibilityMiles          3277 non-null float64
 Mean VisibilityMiles         3277 non-null float64
 Min VisibilityMiles          3277 non-null float64
 Max Wind SpeedMPH            3245 non-null float64
 Mean Wind SpeedMPH           3244 non-null float64
 Max Gust SpeedMPH            3177 non-null float64
PrecipitationIn               3286 non-null object
 CloudCover                   3277 non-null float64
 Events                       1174 non-null object
 WindDirDegrees               3285 non-null float64
dtypes: datetime64[ns](1), float64(20), object(2)
memory usage: 590.7+ KB

Pandas work with memory so what it matters is to have good memory. If you need something like Big Data you can use something similar in Dask or Spark which use similar interface like pandas. 3 to 10 times of the side of your dataframe it is recomended to have in memory.

In [25]:
# just view the first 10 rows
nyc.head(10)

,EST,Max TemperatureF,Mean TemperatureF,Min TemperatureF,Max Dew PointF,MeanDew PointF,Min DewpointF,Max Humidity,Mean Humidity,Min Humidity,...,Max VisibilityMiles,Mean VisibilityMiles,Min VisibilityMiles,Max Wind SpeedMPH,Mean Wind SpeedMPH,Max Gust SpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,2006-01-01,42.0,37.0,32.0,32.0,30.0,28.0,85.0,74.0,62.0,...,10.0,10.0,8.0,9.0,3.0,10.0,0.00,8.0,NaN,276.0
1,2006-01-02,48.0,44.0,39.0,38.0,34.0,29.0,92.0,71.0,49.0,...,10.0,8.0,4.0,18.0,5.0,24.0,0.63,5.0,Rain,76.0
2,2006-01-03,40.0,37.0,33.0,38.0,33.0,26.0,92.0,84.0,75.0,...,10.0,7.0,2.0,28.0,15.0,41.0,1.13,8.0,Rain,39.0
3,2006-01-04,38.0,34.0,29.0,36.0,26.0,19.0,85.0,72.0,59.0,...,10.0,10.0,4.0,15.0,7.0,20.0,0.00,3.0,NaN,70.0
4,2006-01-05,50.0,44.0,37.0,38.0,35.0,32.0,92.0,71.0,50.0,...,10.0,6.0,2.0,15.0,5.0,21.0,0.05,6.0,Rain,251.0
5,2006-01-06,43.0,37.0,30.0,33.0,24.0,14.0,73.0,60.0,47.0,...,10.0,10.0,10.0,17.0,6.0,25.0,0.00,7.0,NaN,317.0
6,2006-01-07,35.0,30.0,25.0,19.0,14.0,11.0,60.0,51.0,41.0,...,10.0,10.0,10.0,15.0,7.0,23.0,0.00,2.0,NaN,267.0
7,2006-01-08,46.0,40.0,34.0,35.0,25.0,19.0,70.0,56.0,41.0,...,10.0,10.0,10.0,13.0,5.0,17.0,0.00,3.0,NaN,192.0
8,2006-01-09,60.0,52.0,43.0,39.0,36.0,30.0,76.0,60.0,44.0,...,10.0,10.0,10.0,15.0,8.0,24.0,0.00,1.0,NaN,249.0
9,2006-01-10,49.0,45.0,41.0,31.0,28.0,26.0,62.0,52.0,42.0,...,10.0,10.0,10.0,10.0,6.0,16.0,0.00,1.0,NaN,261.0

In [26]:
# Transposing the data often makes it easier to view
nyc.T  # nyc.transpose()

,0,1,2,3,4,5,6,7,8,9,...,3277,3278,3279,3280,3281,3282,3283,3284,3285,3286
EST,2006-01-01 00:00:00,2006-01-02 00:00:00,2006-01-03 00:00:00,2006-01-04 00:00:00,2006-01-05 00:00:00,2006-01-06 00:00:00,2006-01-07 00:00:00,2006-01-08 00:00:00,2006-01-09 00:00:00,2006-01-10 00:00:00,...,2014-12-22 00:00:00,2014-12-23 00:00:00,2014-12-24 00:00:00,2014-12-25 00:00:00,2014-12-26 00:00:00,2014-12-27 00:00:00,2014-12-28 00:00:00,2014-12-29 00:00:00,2014-12-30 00:00:00,2014-12-31 00:00:00
Max TemperatureF,42,48,40,38,50,43,35,46,60,49,...,44,46,58,62,50,55,54,44,34,32
Mean TemperatureF,37,44,37,34,44,37,30,40,52,45,...,40,45,51,53,45,50,49,39,31,30
Min TemperatureF,32,39,33,29,37,30,25,34,43,41,...,35,43,44,44,40,44,43,34,28,27
Max Dew PointF,32,38,38,36,38,33,19,35,39,31,...,42,44,57,60,29,35,43,25,17,12
MeanDew PointF,30,34,33,26,35,24,14,25,36,28,...,35,42,47,40,28,31,37,19,13,8
Min DewpointF,28,29,26,19,32,14,11,19,30,26,...,29,41,43,27,27,29,26,15,8,5
Max Humidity,85,92,92,85,92,73,60,70,76,62,...,89,96,100,100,64,53,92,53,58,55
Mean Humidity,74,71,84,72,71,60,51,56,60,52,...,82,91,96,69,53,47,73,42,47,43
Min Humidity,62,49,75,59,50,47,41,41,44,42,...,75,86,92,38,42,41,53,31,36,30
Max Sea Level PressureIn,30.2,30.24,30.05,30.09,29.81,29.82,29.99,30.1,30.25,30.5,...,30.35,30.18,30.08,30.12,30.25,30.27,30.07,30.26,30.4,30.35
Mean Sea Level PressureIn,30.03,30.15,29.93,29.96,29.71,29.72,29.93,30.04,30.01,30.42,...,30.27,30.12,29.79,29.74,30.2,30.19,29.95,30.18,30.36,30.28
Min Sea Level PressureIn,29.83,29.93,29.83,29.79,29.63,29.67,29.84,29.95,29.92,30.28,...,30.16,30.07,29.53,29.48,30.13,30.07,29.88,30.09,30.27,30.18
Max VisibilityMiles,10,10,10,10,10,10,10,10,10,10,...,10,9,7,10,10,10,10,10,10,10
Mean VisibilityMiles,10,8,7,10,6,10,10,10,10,10,...,8,3,3,8,10,10,9,10,10,10
Min VisibilityMiles,8,4,2,4,2,10,10,10,10,10,...,5,2,1,2,10,10,2,10,10,10
Max Wind SpeedMPH,9,18,28,15,15,17,15,13,15,10,...,12,17,12,20,13,14,15,15,10,14
Mean Wind SpeedMPH,3,5,15,7,5,6,7,5,8,6,...,6,8,6,10,6,4,6,5,4,6
Max Gust SpeedMPH,10,24,41,20,21,25,23,17,24,16,...,16,26,17,32,18,25,22,25,17,21
PrecipitationIn,0.00,0.63,1.13,0.00,0.05,0.00,0.00,0.00,0.00,0.00,...,0.04,0.16,0.80,0.09,0.00,0.00,0.10,0.00,0.00,0.00
CloudCover,8,5,8,3,6,7,2,3,1,1,...,8,8,8,5,0,0,5,0,2,2
Events,NaN,Rain,Rain,NaN,Rain,NaN,NaN,NaN,NaN,NaN,...,Rain,Rain,Rain,Rain,NaN,NaN,Rain,NaN,NaN,NaN
WindDirDegrees,276,76,39,70,251,317,267,192,249,261,...,59,67,86,279,272,257,264,308,5,275

In [27]:
# Here is the size (num rows, num cols)
nyc.shape

(3287, 23)

In [28]:
# We can inspect the index
nyc.index

RangeIndex(start=0, stop=3287, step=1)

In [29]:
# We can use the .set_index method to use another column as the index
nyc.set_index('EST')

,Max TemperatureF,Mean TemperatureF,Min TemperatureF,Max Dew PointF,MeanDew PointF,Min DewpointF,Max Humidity,Mean Humidity,Min Humidity,Max Sea Level PressureIn,...,Max VisibilityMiles,Mean VisibilityMiles,Min VisibilityMiles,Max Wind SpeedMPH,Mean Wind SpeedMPH,Max Gust SpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
EST,,,,,,,,,,,,,,,,,,,,,
2006-01-01,42.0,37.0,32.0,32.0,30.0,28.0,85.0,74.0,62.0,30.20,...,10.0,10.0,8.0,9.0,3.0,10.0,0.00,8.0,NaN,276.0
2006-01-02,48.0,44.0,39.0,38.0,34.0,29.0,92.0,71.0,49.0,30.24,...,10.0,8.0,4.0,18.0,5.0,24.0,0.63,5.0,Rain,76.0
2006-01-03,40.0,37.0,33.0,38.0,33.0,26.0,92.0,84.0,75.0,30.05,...,10.0,7.0,2.0,28.0,15.0,41.0,1.13,8.0,Rain,39.0
2006-01-04,38.0,34.0,29.0,36.0,26.0,19.0,85.0,72.0,59.0,30.09,...,10.0,10.0,4.0,15.0,7.0,20.0,0.00,3.0,NaN,70.0
2006-01-05,50.0,44.0,37.0,38.0,35.0,32.0,92.0,71.0,50.0,29.81,...,10.0,6.0,2.0,15.0,5.0,21.0,0.05,6.0,Rain,251.0
2006-01-06,43.0,37.0,30.0,33.0,24.0,14.0,73.0,60.0,47.0,29.82,...,10.0,10.0,10.0,17.0,6.0,25.0,0.00,7.0,NaN,317.0
2006-01-07,35.0,30.0,25.0,19.0,14.0,11.0,60.0,51.0,41.0,29.99,...,10.0,10.0,10.0,15.0,7.0,23.0,0.00,2.0,NaN,267.0
2006-01-08,46.0,40.0,34.0,35.0,25.0,19.0,70.0,56.0,41.0,30.10,...,10.0,10.0,10.0,13.0,5.0,17.0,0.00,3.0,NaN,192.0
2006-01-09,60.0,52.0,43.0,39.0,36.0,30.0,76.0,60.0,44.0,30.25,...,10.0,10.0,10.0,15.0,8.0,24.0,0.00,1.0,NaN,249.0
2006-01-10,49.0,45.0,41.0,31.0,28.0,26.0,62.0,52.0,42.0,30.50,...,10.0,10.0,10.0,10.0,6.0,16.0,0.00,1.0,NaN,261.0
2006-01-11,52.0,47.0,42.0,50.0,42.0,30.0,96.0,79.0,62.0,30.40,...,10.0,4.0,1.0,14.0,4.0,21.0,0.23,7.0,Rain,71.0
2006-01-12,57.0,51.0,45.0,45.0,36.0,31.0,89.0,63.0,36.0,30.03,...,10.0,10.0,10.0,15.0,7.0,20.0,0.00,0.0,NaN,246.0
2006-01-13,54.0,49.0,43.0,52.0,43.0,39.0,96.0,81.0,66.0,30.02,...,10.0,4.0,1.0,12.0,3.0,17.0,0.00,5.0,NaN,171.0
2006-01-14,57.0,44.0,31.0,55.0,49.0,26.0,100.0,91.0,82.0,29.61,...,10.0,5.0,1.0,18.0,9.0,36.0,1.17,8.0,Rain,158.0
2006-01-15,32.0,24.0,16.0,25.0,12.0,-1.0,92.0,62.0,32.0,29.83,...,10.0,6.0,0.0,31.0,13.0,39.0,0.12,5.0,Fog-Snow,298.0
2006-01-16,32.0,24.0,16.0,9.0,5.0,1.0,54.0,44.0,33.0,30.01,...,10.0,10.0,10.0,16.0,8.0,24.0,0.00,0.0,NaN,279.0
2006-01-17,44.0,35.0,26.0,39.0,21.0,8.0,82.0,59.0,35.0,30.18,...,10.0,9.0,2.0,14.0,6.0,20.0,0.16,5.0,Rain,67.0
2006-01-18,58.0,47.0,36.0,55.0,43.0,19.0,93.0,69.0,44.0,30.01,...,10.0,6.0,2.0,28.0,12.0,41.0,0.59,7.0,Rain,217.0
2006-01-19,47.0,41.0,34.0,27.0,21.0,18.0,56.0,47.0,37.0,30.35,...,10.0,10.0,10.0,17.0,8.0,23.0,0.00,0.0,NaN,244.0
2006-01-20,61.0,52.0,42.0,36.0,32.0,28.0,62.0,49.0,36.0,30.21,...,10.0,10.0,10.0,16.0,8.0,23.0,0.00,0.0,NaN,233.0
2006-01-21,63.0,51.0,38.0,42.0,32.0,18.0,61.0,53.0,44.0,30.42,...,10.0,10.0,10.0,26.0,10.0,39.0,0.00,2.0,NaN,263.0
2006-01-22,43.0,38.0,33.0,26.0,16.0,11.0,52.0,40.0,27.0,30.70,...,10.0,10.0,10.0,15.0,7.0,23.0,0.00,1.0,NaN,49.0
2006-01-23,40.0,38.0,35.0,38.0,35.0,28.0,92.0,76.0,59.0,30.43,...,10.0,7.0,2.0,14.0,4.0,17.0,0.68,7.0,Rain-Snow,51.0
2006-01-24,46.0,41.0,35.0,30.0,26.0,15.0,76.0,54.0,31.0,29.94,...,10.0,10.0,10.0,14.0,7.0,18.0,0.00,1.0,NaN,185.0
2006-01-25,42.0,38.0,34.0,32.0,26.0,18.0,82.0,65.0,47.0,29.85,...,10.0,10.0,10.0,22.0,10.0,32.0,0.00,4.0,NaN,266.0
2006-01-26,35.0,31.0,26.0,19.0,14.0,10.0,56.0,47.0,38.0,30.45,...,10.0,10.0,10.0,21.0,14.0,30.0,0.00,1.0,NaN,292.0
2006-01-27,43.0,34.0,24.0,15.0,10.0,4.0,60.0,40.0,19.0,30.57,...,10.0,10.0,10.0,16.0,8.0,22.0,0.00,0.0,NaN,274.0
2006-01-28,58.0,48.0,37.0,27.0,20.0,14.0,40.0,33.0,26.0,30.35,...,10.0,10.0,10.0,13.0,6.0,21.0,0.00,0.0,NaN,243.0
2006-01-29,53.0,49.0,44.0,49.0,39.0,26.0,93.0,66.0,38.0,30.12,...,10.0,8.0,2.0,13.0,5.0,20.0,0.14,5.0,Rain,169.0
2006-01-30,64.0,53.0,41.0,48.0,43.0,39.0,96.0,70.0,43.0,29.83,...,10.0,6.0,2.0,20.0,8.0,28.0,0.01,4.0,NaN,64.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-12-02,43.0,39.0,35.0,40.0,30.0,17.0,89.0,67.0,44.0,30.63,...,10.0,8.0,2.0,17.0,9.0,26.0,0.08,7.0,Rain,70.0
2014-12-03,46.0,44.0,41.0,43.0,38.0,24.0,92.0,73.0,53.0,30.27,...,10.0,6.0,2.0,16.0,8.0,26.0,0.06,7.0,Rain,276.0
2014-12-04,45.0,41.0,37.0,24.0,21.0,17.0,59.0,48.0,36.0,30.52,...,10.0,10.0,10.0,13.0,6.0,19.0,0.00,0.0,NaN,304.0
2014-12-05,44.0,39.0,34.0,41.0,33.0,19.0,89.0,69.0,48.0,30.61,...,10.0,6.0,1.0,17.0,6.0,21.0,0.51,6.0,Rain,50.0
2014-12-06,50.0,45.0,39.0,47.0,42.0,36.0,96.0,88.0,80.0,30.36,...,8.0,3.0,1.0,17.0,4.0,30.0,1.22,8.0,Rain,36.0
2014-12-07,42.0,36.0,30.0,35.0,18.0,0.0,92.0,62.0,32.0,30.61,...,10.0,10.0,10.0,25.0,12.0,40.0,0.04,1.0,Rain,28.0
2014-12-08,37.0,31.0,24.0,30.0,17.0,-1.0,75.0,51.0,27.0,30.68,...,10.0,10.0,10.0,20.0,12.0,29.0,0.00,6.0,NaN,60.0
2014-12-09,42.0,39.0,36.0,38.0,36.0,30.0,92.0,81.0,70.0,30.31,...,10.0,5.0,1.0,22.0,10.0,32.0,2.54,8.0,Rain,36.0
2014-12-10,40.0,36.0,32.0,36.0,31.0,23.0,89.0,74.0,59.0,29.69,...,10.0,6.0,1.0,16.0,8.0,24.0,0.08,8.0,Rain-Snow,295.0
2014-12-11,38.0,35.0,31.0,26.0,23.0,20.0,75.0,62.0,48.0,29.87,...,10.0,9.0,2.0,17.0,8.0,25.0,0.01,7.0,Snow,276.0
2014-12-12,38.0,35.0,32.0,23.0,21.0,19.0,61.0,57.0,52.0,30.00,...,10.0,10.0,10.0,15.0,8.0,25.0,0.00,6.0,NaN,303.0
2014-12-13,44.0,39.0,34.0,28.0,25.0,21.0,64.0,54.0,43.0,29.99,...,10.0,10.0,10.0,16.0,9.0,28.0,0.00,2.0,NaN,307.0
2014-12-14,46.0,42.0,38.0,29.0,29.0,28.0,70.0,60.0,49.0,29.97,...,10.0,10.0,10.0,13.0,6.0,20.0,0.00,4.0,NaN,306.0
2014-12-15,48.0,43.0,37.0,34.0,29.0,28.0,70.0,58.0,46.0,30.12,...,10.0,10.0,10.0,8.0,3.0,12.0,0.00,0.0,NaN,333.0
2014-12-16,49.0,44.0,38.0,43.0,39.0,32.0,86.0,76.0,65.0,30.11,...,10.0,6.0,2.0,12.0,4.0,14.0,0.20,7.0,Rain,75.0
2014-12-17,54.0,48.0,42.0,43.0,39.0,26.0,92.0,73.0,53.0,29.89,...,10.0,7.0,2.0,16.0,6.0,26.0,0.02,7.0,Rain,294.0
2014-12-18,42.0,40.0,37.0,25.0,23.0,21.0,59.0,52.0,45.0,29.99,...,10.0,10.0,10.0,16.0,9.0,28.0,0.00,6.0,NaN,293.0
2014-12-19,38.0,35.0,31.0,25.0,21.0,19.0,63.0,56.0,48.0,30.21,...,10.0,10.0,10.0,14.0,7.0,24.0,0.00,5.0,NaN,307.0
2014-12-20,33.0,32.0,30.0,21.0,19.0,18.0,63.0,57.0,51.0,30.31,...,10.0,10.0,10.0,12.0,5.0,15.0,0.00,8.0,NaN,10.0
2014-12-21,36.0,34.0,31.0,29.0,25.0,21.0,82.0,73.0,63.0,30.36,...,10.0,9.0,6.0,9.0,5.0,13.0,T,8.0,Snow,338.0
2014-12-22,44.0,40.0,35.0,42.0,35.0,29.0,89.0,82.0,75.0,30.35,...,10.0,8.0,5.0,12.0,6.0,16.0,0.04,8.0,Rain,59.0
2014-12-23,46.0,45.0,43.0,44.0,42.0,41.0,96.0,91.0,86.0,30.18,...,9.0,3.0,2.0,17.0,8.0,26.0,0.16,8.0,Rain,67.0
2014-12-24,58.0,51.0,44.0,57.0,47.0,43.0,100.0,96.0,92.0,30.08,...,7.0,3.0,1.0,12.0,6.0,17.0,0.80,8.0,Rain,86.0
2014-12-25,62.0,53.0,44.0,60.0,40.0,27.0,100.0,69.0,38.0,30.12,...,10.0,8.0,2.0,20.0,10.0,32.0,0.09,5.0,Rain,279.0
2014-12-26,50.0,45.0,40.0,29.0,28.0,27.0,64.0,53.0,42.0,30.25,...,10.0,10.0,10.0,13.0,6.0,18.0,0.00,0.0,NaN,272.0
2014-12-27,55.0,50.0,44.0,35.0,31.0,29.0,53.0,47.0,41.0,30.27,...,10.0,10.0,10.0,14.0,4.0,25.0,0.00,0.0,NaN,257.0
2014-12-28,54.0,49.0,43.0,43.0,37.0,26.0,92.0,73.0,53.0,30.07,...,10.0,9.0,2.0,15.0,6.0,22.0,0.10,5.0,Rain,264.0
2014-12-29,44.0,39.0,34.0,25.0,19.0,15.0,53.0,42.0,31.0,30.26,...,10.0,10.0,10.0,15.0,5.0,25.0,0.00,0.0,NaN,308.0
2014-12-30,34.0,31.0,28.0,17.0,13.0,8.0,58.0,47.0,36.0,30.40,...,10.0,10.0,10.0,10.0,4.0,17.0,0.00,2.0,NaN,5.0
2014-12-31,32.0,30.0,27.0,12.0,8.0,5.0,55.0,43.0,30.0,30.35,...,10.0,10.0,10.0,14.0,6.0,21.0,0.00,2.0,NaN,275.0

In [30]:
# undo .set_index with .reset_index
nyc.set_index('EST').reset_index()
nyc

,EST,Max TemperatureF,Mean TemperatureF,Min TemperatureF,Max Dew PointF,MeanDew PointF,Min DewpointF,Max Humidity,Mean Humidity,Min Humidity,...,Max VisibilityMiles,Mean VisibilityMiles,Min VisibilityMiles,Max Wind SpeedMPH,Mean Wind SpeedMPH,Max Gust SpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,2006-01-01,42.0,37.0,32.0,32.0,30.0,28.0,85.0,74.0,62.0,...,10.0,10.0,8.0,9.0,3.0,10.0,0.00,8.0,NaN,276.0
1,2006-01-02,48.0,44.0,39.0,38.0,34.0,29.0,92.0,71.0,49.0,...,10.0,8.0,4.0,18.0,5.0,24.0,0.63,5.0,Rain,76.0
2,2006-01-03,40.0,37.0,33.0,38.0,33.0,26.0,92.0,84.0,75.0,...,10.0,7.0,2.0,28.0,15.0,41.0,1.13,8.0,Rain,39.0
3,2006-01-04,38.0,34.0,29.0,36.0,26.0,19.0,85.0,72.0,59.0,...,10.0,10.0,4.0,15.0,7.0,20.0,0.00,3.0,NaN,70.0
4,2006-01-05,50.0,44.0,37.0,38.0,35.0,32.0,92.0,71.0,50.0,...,10.0,6.0,2.0,15.0,5.0,21.0,0.05,6.0,Rain,251.0
5,2006-01-06,43.0,37.0,30.0,33.0,24.0,14.0,73.0,60.0,47.0,...,10.0,10.0,10.0,17.0,6.0,25.0,0.00,7.0,NaN,317.0
6,2006-01-07,35.0,30.0,25.0,19.0,14.0,11.0,60.0,51.0,41.0,...,10.0,10.0,10.0,15.0,7.0,23.0,0.00,2.0,NaN,267.0
7,2006-01-08,46.0,40.0,34.0,35.0,25.0,19.0,70.0,56.0,41.0,...,10.0,10.0,10.0,13.0,5.0,17.0,0.00,3.0,NaN,192.0
8,2006-01-09,60.0,52.0,43.0,39.0,36.0,30.0,76.0,60.0,44.0,...,10.0,10.0,10.0,15.0,8.0,24.0,0.00,1.0,NaN,249.0
9,2006-01-10,49.0,45.0,41.0,31.0,28.0,26.0,62.0,52.0,42.0,...,10.0,10.0,10.0,10.0,6.0,16.0,0.00,1.0,NaN,261.0
10,2006-01-11,52.0,47.0,42.0,50.0,42.0,30.0,96.0,79.0,62.0,...,10.0,4.0,1.0,14.0,4.0,21.0,0.23,7.0,Rain,71.0
11,2006-01-12,57.0,51.0,45.0,45.0,36.0,31.0,89.0,63.0,36.0,...,10.0,10.0,10.0,15.0,7.0,20.0,0.00,0.0,NaN,246.0
12,2006-01-13,54.0,49.0,43.0,52.0,43.0,39.0,96.0,81.0,66.0,...,10.0,4.0,1.0,12.0,3.0,17.0,0.00,5.0,NaN,171.0
13,2006-01-14,57.0,44.0,31.0,55.0,49.0,26.0,100.0,91.0,82.0,...,10.0,5.0,1.0,18.0,9.0,36.0,1.17,8.0,Rain,158.0
14,2006-01-15,32.0,24.0,16.0,25.0,12.0,-1.0,92.0,62.0,32.0,...,10.0,6.0,0.0,31.0,13.0,39.0,0.12,5.0,Fog-Snow,298.0
15,2006-01-16,32.0,24.0,16.0,9.0,5.0,1.0,54.0,44.0,33.0,...,10.0,10.0,10.0,16.0,8.0,24.0,0.00,0.0,NaN,279.0
16,2006-01-17,44.0,35.0,26.0,39.0,21.0,8.0,82.0,59.0,35.0,...,10.0,9.0,2.0,14.0,6.0,20.0,0.16,5.0,Rain,67.0
17,2006-01-18,58.0,47.0,36.0,55.0,43.0,19.0,93.0,69.0,44.0,...,10.0,6.0,2.0,28.0,12.0,41.0,0.59,7.0,Rain,217.0
18,2006-01-19,47.0,41.0,34.0,27.0,21.0,18.0,56.0,47.0,37.0,...,10.0,10.0,10.0,17.0,8.0,23.0,0.00,0.0,NaN,244.0
19,2006-01-20,61.0,52.0,42.0,36.0,32.0,28.0,62.0,49.0,36.0,...,10.0,10.0,10.0,16.0,8.0,23.0,0.00,0.0,NaN,233.0
20,2006-01-21,63.0,51.0,38.0,42.0,32.0,18.0,61.0,53.0,44.0,...,10.0,10.0,10.0,26.0,10.0,39.0,0.00,2.0,NaN,263.0
21,2006-01-22,43.0,38.0,33.0,26.0,16.0,11.0,52.0,40.0,27.0,...,10.0,10.0,10.0,15.0,7.0,23.0,0.00,1.0,NaN,49.0
22,2006-01-23,40.0,38.0,35.0,38.0,35.0,28.0,92.0,76.0,59.0,...,10.0,7.0,2.0,14.0,4.0,17.0,0.68,7.0,Rain-Snow,51.0
23,2006-01-24,46.0,41.0,35.0,30.0,26.0,15.0,76.0,54.0,31.0,...,10.0,10.0,10.0,14.0,7.0,18.0,0.00,1.0,NaN,185.0
24,2006-01-25,42.0,38.0,34.0,32.0,26.0,18.0,82.0,65.0,47.0,...,10.0,10.0,10.0,22.0,10.0,32.0,0.00,4.0,NaN,266.0
25,2006-01-26,35.0,31.0,26.0,19.0,14.0,10.0,56.0,47.0,38.0,...,10.0,10.0,10.0,21.0,14.0,30.0,0.00,1.0,NaN,292.0
26,2006-01-27,43.0,34.0,24.0,15.0,10.0,4.0,60.0,40.0,19.0,...,10.0,10.0,10.0,16.0,8.0,22.0,0.00,0.0,NaN,274.0
27,2006-01-28,58.0,48.0,37.0,27.0,20.0,14.0,40.0,33.0,26.0,...,10.0,10.0,10.0,13.0,6.0,21.0,0.00,0.0,NaN,243.0
28,2006-01-29,53.0,49.0,44.0,49.0,39.0,26.0,93.0,66.0,38.0,...,10.0,8.0,2.0,13.0,5.0,20.0,0.14,5.0,Rain,169.0
29,2006-01-30,64.0,53.0,41.0,48.0,43.0,39.0,96.0,70.0,43.0,...,10.0,6.0,2.0,20.0,8.0,28.0,0.01,4.0,NaN,64.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3257,2014-12-02,43.0,39.0,35.0,40.0,30.0,17.0,89.0,67.0,44.0,...,10.0,8.0,2.0,17.0,9.0,26.0,0.08,7.0,Rain,70.0
3258,2014-12-03,46.0,44.0,41.0,43.0,38.0,24.0,92.0,73.0,53.0,...,10.0,6.0,2.0,16.0,8.0,26.0,0.06,7.0,Rain,276.0
3259,2014-12-04,45.0,41.0,37.0,24.0,21.0,17.0,59.0,48.0,36.0,...,10.0,10.0,10.0,13.0,6.0,19.0,0.00,0.0,NaN,304.0
3260,2014-12-05,44.0,39.0,34.0,41.0,33.0,19.0,89.0,69.0,48.0,...,10.0,6.0,1.0,17.0,6.0,21.0,0.51,6.0,Rain,50.0
3261,2014-12-06,50.0,45.0,39.0,47.0,42.0,36.0,96.0,88.0,80.0,...,8.0,3.0,1.0,17.0,4.0,30.0,1.22,8.0,Rain,36.0
3262,2014-12-07,42.0,36.0,30.0,35.0,18.0,0.0,92.0,62.0,32.0,...,10.0,10.0,10.0,25.0,12.0,40.0,0.04,1.0,Rain,28.0
3263,2014-12-08,37.0,31.0,24.0,30.0,17.0,-1.0,75.0,51.0,27.0,...,10.0,10.0,10.0,20.0,12.0,29.0,0.00,6.0,NaN,60.0
3264,2014-12-09,42.0,39.0,36.0,38.0,36.0,30.0,92.0,81.0,70.0,...,10.0,5.0,1.0,22.0,10.0,32.0,2.54,8.0,Rain,36.0
3265,2014-12-10,40.0,36.0,32.0,36.0,31.0,23.0,89.0,74.0,59.0,...,10.0,6.0,1.0,16.0,8.0,24.0,0.08,8.0,Rain-Snow,295.0
3266,2014-12-11,38.0,35.0,31.0,26.0,23.0,20.0,75.0,62.0,48.0,...,10.0,9.0,2.0,17.0,8.0,25.0,0.01,7.0,Snow,276.0
3267,2014-12-12,38.0,35.0,32.0,23.0,21.0,19.0,61.0,57.0,52.0,...,10.0,10.0,10.0,15.0,8.0,25.0,0.00,6.0,NaN,303.0
3268,2014-12-13,44.0,39.0,34.0,28.0,25.0,21.0,64.0,54.0,43.0,...,10.0,10.0,10.0,16.0,9.0,28.0,0.00,2.0,NaN,307.0
3269,2014-12-14,46.0,42.0,38.0,29.0,29.0,28.0,70.0,60.0,49.0,...,10.0,10.0,10.0,13.0,6.0,20.0,0.00,4.0,NaN,306.0
3270,2014-12-15,48.0,43.0,37.0,34.0,29.0,28.0,70.0,58.0,46.0,...,10.0,10.0,10.0,8.0,3.0,12.0,0.00,0.0,NaN,333.0
3271,2014-12-16,49.0,44.0,38.0,43.0,39.0,32.0,86.0,76.0,65.0,...,10.0,6.0,2.0,12.0,4.0,14.0,0.20,7.0,Rain,75.0
3272,2014-12-17,54.0,48.0,42.0,43.0,39.0,26.0,92.0,73.0,53.0,...,10.0,7.0,2.0,16.0,6.0,26.0,0.02,7.0,Rain,294.0
3273,2014-12-18,42.0,40.0,37.0,25.0,23.0,21.0,59.0,52.0,45.0,...,10.0,10.0,10.0,16.0,9.0,28.0,0.00,6.0,NaN,293.0
3274,2014-12-19,38.0,35.0,31.0,25.0,21.0,19.0,63.0,56.0,48.0,...,10.0,10.0,10.0,14.0,7.0,24.0,0.00,5.0,NaN,307.0
3275,2014-12-20,33.0,32.0,30.0,21.0,19.0,18.0,63.0,57.0,51.0,...,10.0,10.0,10.0,12.0,5.0,15.0,0.00,8.0,NaN,10.0
3276,2014-12-21,36.0,34.0,31.0,29.0,25.0,21.0,82.0,73.0,63.0,...,10.0,9.0,6.0,9.0,5.0,13.0,T,8.0,Snow,338.0
3277,2014-12-22,44.0,40.0,35.0,42.0,35.0,29.0,89.0,82.0,75.0,...,10.0,8.0,5.0,12.0,6.0,16.0,0.04,8.0,Rain,59.0
3278,2014-12-23,46.0,45.0,43.0,44.0,42.0,41.0,96.0,91.0,86.0,...,9.0,3.0,2.0,17.0,8.0,26.0,0.16,8.0,Rain,67.0
3279,2014-12-24,58.0,51.0,44.0,57.0,47.0,43.0,100.0,96.0,92.0,...,7.0,3.0,1.0,12.0,6.0,17.0,0.80,8.0,Rain,86.0
3280,2014-12-25,62.0,53.0,44.0,60.0,40.0,27.0,100.0,69.0,38.0,...,10.0,8.0,2.0,20.0,10.0,32.0,0.09,5.0,Rain,279.0
3281,2014-12-26,50.0,45.0,40.0,29.0,28.0,27.0,64.0,53.0,42.0,...,10.0,10.0,10.0,13.0,6.0,18.0,0.00,0.0,NaN,272.0
3282,2014-12-27,55.0,50.0,44.0,35.0,31.0,29.0,53.0,47.0,41.0,...,10.0,10.0,10.0,14.0,4.0,25.0,0.00,0.0,NaN,257.0
3283,2014-12-28,54.0,49.0,43.0,43.0,37.0,26.0,92.0,73.0,53.0,...,10.0,9.0,2.0,15.0,6.0,22.0,0.10,5.0,Rain,264.0
3284,2014-12-29,44.0,39.0,34.0,25.0,19.0,15.0,53.0,42.0,31.0,...,10.0,10.0,10.0,15.0,5.0,25.0,0.00,0.0,NaN,308.0
3285,2014-12-30,34.0,31.0,28.0,17.0,13.0,8.0,58.0,47.0,36.0,...,10.0,10.0,10.0,10.0,4.0,17.0,0.00,2.0,NaN,5.0
3286,2014-12-31,32.0,30.0,27.0,12.0,8.0,5.0,55.0,43.0,30.0,...,10.0,10.0,10.0,14.0,6.0,21.0,0.00,2.0,NaN,275.0

## Inspecting Data Assignment

Now it is your turn to inspect the El Nino data.
 
* What are the columns of the dataframe?
* What are the types of the columns?
* How would you print the first 10 rows of data?
* How would you transpose the data?
* What is the shape of the data?
* How would we inspect the index?

In [31]:
nino.columns

Index(['obs', 'year', 'month', 'day', 'date', 'latitude', 'longitude',
       'zon.winds', 'mer.winds', 'humidity', 'air temp.', 's.s.temp.'],
      dtype='object')

In [32]:
nino.dtypes

obs                   int64
year                  int64
month                 int64
day                   int64
date         datetime64[ns]
latitude            float64
longitude           float64
zon.winds           float64
mer.winds           float64
humidity            float64
air temp.           float64
s.s.temp.           float64
dtype: object

In [33]:
nino.head()

,obs,year,month,day,date,latitude,longitude,zon.winds,mer.winds,humidity,air temp.,s.s.temp.
0,1,80,3,7,1980-03-07,-0.02,-109.46,-6.8,0.7,NaN,26.14,26.24
1,2,80,3,8,1980-03-08,-0.02,-109.46,-4.9,1.1,NaN,25.66,25.97
2,3,80,3,9,1980-03-09,-0.02,-109.46,-4.5,2.2,NaN,25.69,25.28
3,4,80,3,10,1980-03-10,-0.02,-109.46,-3.8,1.9,NaN,25.57,24.31
4,5,80,3,11,1980-03-11,-0.02,-109.46,-4.2,1.5,NaN,25.30,23.19

In [34]:
nino.T

,0,1,2,3,4,5,6,7,8,9,...,178070,178071,178072,178073,178074,178075,178076,178077,178078,178079
obs,1,2,3,4,5,6,7,8,9,10,...,178071,178072,178073,178074,178075,178076,178077,178078,178079,178080
year,80,80,80,80,80,80,80,80,80,80,...,98,98,98,98,98,98,98,98,98,98
month,3,3,3,3,3,3,3,3,3,3,...,6,6,6,6,6,6,6,6,6,6
day,7,8,9,10,11,12,13,14,15,16,...,6,7,8,9,10,11,12,13,14,15
date,1980-03-07 00:00:00,1980-03-08 00:00:00,1980-03-09 00:00:00,1980-03-10 00:00:00,1980-03-11 00:00:00,1980-03-12 00:00:00,1980-03-13 00:00:00,1980-03-14 00:00:00,1980-03-15 00:00:00,1980-03-16 00:00:00,...,1998-06-06 00:00:00,1998-06-07 00:00:00,1998-06-08 00:00:00,1998-06-09 00:00:00,1998-06-10 00:00:00,1998-06-11 00:00:00,1998-06-12 00:00:00,1998-06-13 00:00:00,1998-06-14 00:00:00,1998-06-15 00:00:00
latitude,-0.02,-0.02,-0.02,-0.02,-0.02,-0.02,-0.02,-0.02,-0.02,-0.02,...,8.96,8.95,8.96,8.98,8.95,8.96,8.96,8.95,8.96,8.95
longitude,-109.46,-109.46,-109.46,-109.46,-109.46,-109.46,-109.46,-109.46,-109.46,-109.46,...,-140.33,-140.33,-140.33,-140.33,-140.33,-140.33,-140.32,-140.34,-140.33,-140.33
zon.winds,-6.8,-4.9,-4.5,-3.8,-4.2,-4.4,-3.2,-3.1,-3,-1.2,...,-6.6,-8.4,-8.4,-6.5,-6.8,-5.1,-4.3,-6.1,-4.9,NaN
mer.winds,0.7,1.1,2.2,1.9,1.5,0.3,0.1,0.6,1,1,...,-4.3,-4.2,-5,-5.9,-5.3,-0.4,-3.3,-4.8,-2.3,NaN
humidity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,81.3,83.5,79.2,75.4,81.3,94.1,93.2,81.3,76.2,NaN
air temp.,26.14,25.66,25.69,25.57,25.3,24.72,24.66,25.17,25.59,26.71,...,27.71,27.91,27.87,27.56,27.52,26.04,25.8,27.17,27.36,27.09
s.s.temp.,26.24,25.97,25.28,24.31,23.19,23.64,24.34,24.14,24.24,25.94,...,28.28,28.26,28.22,28.22,28.17,28.14,27.87,27.93,28.03,28.09

In [35]:
nino.shape

(178080, 12)

In [36]:
nino.index

RangeIndex(start=0, stop=178080, step=1)

# Tweak Data

  *In Data Science, 80% of time spent prepare data, 20% of time spent complain about need for  prepare data.*
  
  -@bigdataborat
  
Let's see how we spend 80% of our time.

In [37]:
# I like to start by inspecting the columns. Pandas will try to 
# infer types from CSV files, but doesn't always do the right thing.
# Sometimes the data is just messy.
nyc.dtypes

EST                           datetime64[ns]
Max TemperatureF                     float64
Mean TemperatureF                    float64
Min TemperatureF                     float64
Max Dew PointF                       float64
MeanDew PointF                       float64
Min DewpointF                        float64
Max Humidity                         float64
 Mean Humidity                       float64
 Min Humidity                        float64
 Max Sea Level PressureIn            float64
 Mean Sea Level PressureIn           float64
 Min Sea Level PressureIn            float64
 Max VisibilityMiles                 float64
 Mean VisibilityMiles                float64
 Min VisibilityMiles                 float64
 Max Wind SpeedMPH                   float64
 Mean Wind SpeedMPH                  float64
 Max Gust SpeedMPH                   float64
PrecipitationIn                       object
 CloudCover                          float64
 Events                               object
 WindDirDegrees                      float64
dtype: object

In [38]:
# See those spaces in front of some of the Columns?
# Remove spaces from front/end of column names
nyc.columns = [x.strip() for x in nyc.columns]

In [39]:
# Use underscores to enable attribute access/jupyter completion
nyc.columns = [x.replace(' ', '_') for x in nyc.columns]

In [40]:
# For non-numeric columns, .value_counts gives us 
# counts of the data. One would think that 
# PrecipitationIn should be numeric....
nyc.PrecipitationIn.value_counts()

0.00    1952
T        201
0.01     112
0.02      59
0.03      58
0.04      45
0.06      44
0.05      38
0.08      27
0.07      26
0.09      23
0.19      20
0.16      19
0.13      19
0.14      19
0.11      17
0.10      16
0.18      15
0.15      15
0.21      13
0.23      12
0.33      12
0.12      11
0.30      11
0.22      10
0.45      10
0.32      10
0.24      10
0.35       9
0.50       9
        ...
1.95       1
1.10       1
2.46       1
1.26       1
1.04       1
2.30       1
1.59       1
0.79       1
1.22       1
1.62       1
1.08       1
1.40       1
7.57       1
0.80       1
1.98       1
0.48       1
1.94       1
5.81       1
2.54       1
1.42       1
3.22       1
0.96       1
1.11       1
3.02       1
1.58       1
2.01       1
2.04       1
1.36       1
1.69       1
0.76       1
Name: PrecipitationIn, Length: 196, dtype: int64

In [41]:
# There is a "T" in there. Trace? 
# Convert "T" to 0.001
nyc.PrecipitationIn.replace("T", '0.001')
# Convert to numeric data
nyc.PrecipitationIn = pd.to_numeric(nyc.PrecipitationIn.replace("T", '0.001'))

In [42]:
nyc.PrecipitationIn.value_counts()

0.000    1952
0.001     201
0.010     112
0.020      59
0.030      58
0.040      45
0.060      44
0.050      38
0.080      27
0.070      26
0.090      23
0.190      20
0.140      19
0.160      19
0.130      19
0.110      17
0.100      16
0.180      15
0.150      15
0.210      13
0.230      12
0.330      12
0.300      11
0.120      11
0.320      10
0.240      10
0.220      10
0.450      10
0.500       9
0.350       9
         ...
1.820       1
2.460       1
1.320       1
5.810       1
1.950       1
1.190       1
1.100       1
2.590       1
1.940       1
1.360       1
3.600       1
3.220       1
1.680       1
0.480       1
4.970       1
4.160       1
2.880       1
1.420       1
1.080       1
1.400       1
1.070       1
3.450       1
2.420       1
1.660       1
1.690       1
2.030       1
1.010       1
0.790       1
1.920       1
7.570       1
Name: PrecipitationIn, Length: 196, dtype: int64

In [43]:
nyc.Events.value_counts(dropna=False)

NaN              2113
Rain              803
Fog-Rain          189
Snow               74
Fog-Snow           39
Rain-Snow          31
Fog-Rain-Snow      22
Fog                15
Thunderstorm        1
Name: Events, dtype: int64

In [44]:
# can perform string operations on string columns off of the "str" attribute
nyc.Events.str.upper()

0             NaN
1            RAIN
2            RAIN
3             NaN
4            RAIN
5             NaN
6             NaN
7             NaN
8             NaN
9             NaN
10           RAIN
11            NaN
12            NaN
13           RAIN
14       FOG-SNOW
15            NaN
16           RAIN
17           RAIN
18            NaN
19            NaN
20            NaN
21            NaN
22      RAIN-SNOW
23            NaN
24            NaN
25            NaN
26            NaN
27            NaN
28           RAIN
29            NaN
          ...
3257         RAIN
3258         RAIN
3259          NaN
3260         RAIN
3261         RAIN
3262         RAIN
3263          NaN
3264         RAIN
3265    RAIN-SNOW
3266         SNOW
3267          NaN
3268          NaN
3269          NaN
3270          NaN
3271         RAIN
3272         RAIN
3273          NaN
3274          NaN
3275          NaN
3276         SNOW
3277         RAIN
3278         RAIN
3279         RAIN
3280         RAIN
3281          NaN
3282          NaN
3283         RAIN
3284          NaN
3285          NaN
3286          NaN
Name: Events, Length: 3287, dtype: object

In [45]:
# Looks like the type of this column is mixed
type(nyc.Events[0])

float

In [46]:
set(nyc.Events.apply(type))

{str, float}

In [47]:
# Replace nan with ''
nyc['Events'] = nyc.Events.fillna('')

In [48]:
set(nyc.Events.apply(type))

{str}

In [49]:
# convert inches to cm
# If we multiply a column (Series), we are *broadcasting*
# the operation to every cell
nyc.PrecipitationIn * 2.54

0       0.00000
1       1.60020
2       2.87020
3       0.00000
4       0.12700
5       0.00000
6       0.00000
7       0.00000
8       0.00000
9       0.00000
10      0.58420
11      0.00000
12      0.00000
13      2.97180
14      0.30480
15      0.00000
16      0.40640
17      1.49860
18      0.00000
19      0.00000
20      0.00000
21      0.00000
22      1.72720
23      0.00000
24      0.00000
25      0.00000
26      0.00000
27      0.00000
28      0.35560
29      0.02540
         ...
3257    0.20320
3258    0.15240
3259    0.00000
3260    1.29540
3261    3.09880
3262    0.10160
3263    0.00000
3264    6.45160
3265    0.20320
3266    0.02540
3267    0.00000
3268    0.00000
3269    0.00000
3270    0.00000
3271    0.50800
3272    0.05080
3273    0.00000
3274    0.00000
3275    0.00000
3276    0.00254
3277    0.10160
3278    0.40640
3279    2.03200
3280    0.22860
3281    0.00000
3282    0.00000
3283    0.25400
3284    0.00000
3285    0.00000
3286    0.00000
Name: PrecipitationIn, Length: 3287, dtype: float64

In [50]:
# can also apply an arbitrary function, though this will be slow as it is not vectorized
#   map - works with a dictionary (mapping value to new value),  series (like dict), function
#   apply - only works with function as a parameter. Allows extra parameters
#   aggregate (agg) - works with function or list of functions. If reducing function, returns a scalar.
#   transform - wraps agg and won't do a reduction
def to_cm(val):
    return val * 2.54

nyc.PrecipitationIn.transform(to_cm)

0       0.00000
1       1.60020
2       2.87020
3       0.00000
4       0.12700
5       0.00000
6       0.00000
7       0.00000
8       0.00000
9       0.00000
10      0.58420
11      0.00000
12      0.00000
13      2.97180
14      0.30480
15      0.00000
16      0.40640
17      1.49860
18      0.00000
19      0.00000
20      0.00000
21      0.00000
22      1.72720
23      0.00000
24      0.00000
25      0.00000
26      0.00000
27      0.00000
28      0.35560
29      0.02540
         ...
3257    0.20320
3258    0.15240
3259    0.00000
3260    1.29540
3261    3.09880
3262    0.10160
3263    0.00000
3264    6.45160
3265    0.20320
3266    0.02540
3267    0.00000
3268    0.00000
3269    0.00000
3270    0.00000
3271    0.50800
3272    0.05080
3273    0.00000
3274    0.00000
3275    0.00000
3276    0.00254
3277    0.10160
3278    0.40640
3279    2.03200
3280    0.22860
3281    0.00000
3282    0.00000
3283    0.25400
3284    0.00000
3285    0.00000
3286    0.00000
Name: PrecipitationIn, Length: 3287, dtype: float64

In [51]:
%%timeit
nyc.PrecipitationIn.map(to_cm)

943 ¬µs ¬± 45.3 ¬µs per loop (mean ¬± std. dev. of 7 runs, 1000 loops each)

In [52]:
%%timeit
nyc.PrecipitationIn.transform(to_cm)

990 ¬µs ¬± 48.7 ¬µs per loop (mean ¬± std. dev. of 7 runs, 1000 loops each)

In [53]:
%%timeit
nyc.PrecipitationIn*2.54

91.2 ¬µs ¬± 826 ns per loop (mean ¬± std. dev. of 7 runs, 10000 loops each)

Check if you always can put the things in a vector operations instead of using transform

In [54]:
# can add and drop columns (axis=1 means along the columns axis)
# Note that we can access some columns with attribute access
# We can only set w/ attribute access on an existing column!
nyc['State'] = 'NYC'
nyc = nyc.drop(['State'], axis=1)
nyc

,EST,Max_TemperatureF,Mean_TemperatureF,Min_TemperatureF,Max_Dew_PointF,MeanDew_PointF,Min_DewpointF,Max_Humidity,Mean_Humidity,Min_Humidity,...,Max_VisibilityMiles,Mean_VisibilityMiles,Min_VisibilityMiles,Max_Wind_SpeedMPH,Mean_Wind_SpeedMPH,Max_Gust_SpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,2006-01-01,42.0,37.0,32.0,32.0,30.0,28.0,85.0,74.0,62.0,...,10.0,10.0,8.0,9.0,3.0,10.0,0.000,8.0,,276.0
1,2006-01-02,48.0,44.0,39.0,38.0,34.0,29.0,92.0,71.0,49.0,...,10.0,8.0,4.0,18.0,5.0,24.0,0.630,5.0,Rain,76.0
2,2006-01-03,40.0,37.0,33.0,38.0,33.0,26.0,92.0,84.0,75.0,...,10.0,7.0,2.0,28.0,15.0,41.0,1.130,8.0,Rain,39.0
3,2006-01-04,38.0,34.0,29.0,36.0,26.0,19.0,85.0,72.0,59.0,...,10.0,10.0,4.0,15.0,7.0,20.0,0.000,3.0,,70.0
4,2006-01-05,50.0,44.0,37.0,38.0,35.0,32.0,92.0,71.0,50.0,...,10.0,6.0,2.0,15.0,5.0,21.0,0.050,6.0,Rain,251.0
5,2006-01-06,43.0,37.0,30.0,33.0,24.0,14.0,73.0,60.0,47.0,...,10.0,10.0,10.0,17.0,6.0,25.0,0.000,7.0,,317.0
6,2006-01-07,35.0,30.0,25.0,19.0,14.0,11.0,60.0,51.0,41.0,...,10.0,10.0,10.0,15.0,7.0,23.0,0.000,2.0,,267.0
7,2006-01-08,46.0,40.0,34.0,35.0,25.0,19.0,70.0,56.0,41.0,...,10.0,10.0,10.0,13.0,5.0,17.0,0.000,3.0,,192.0
8,2006-01-09,60.0,52.0,43.0,39.0,36.0,30.0,76.0,60.0,44.0,...,10.0,10.0,10.0,15.0,8.0,24.0,0.000,1.0,,249.0
9,2006-01-10,49.0,45.0,41.0,31.0,28.0,26.0,62.0,52.0,42.0,...,10.0,10.0,10.0,10.0,6.0,16.0,0.000,1.0,,261.0
10,2006-01-11,52.0,47.0,42.0,50.0,42.0,30.0,96.0,79.0,62.0,...,10.0,4.0,1.0,14.0,4.0,21.0,0.230,7.0,Rain,71.0
11,2006-01-12,57.0,51.0,45.0,45.0,36.0,31.0,89.0,63.0,36.0,...,10.0,10.0,10.0,15.0,7.0,20.0,0.000,0.0,,246.0
12,2006-01-13,54.0,49.0,43.0,52.0,43.0,39.0,96.0,81.0,66.0,...,10.0,4.0,1.0,12.0,3.0,17.0,0.000,5.0,,171.0
13,2006-01-14,57.0,44.0,31.0,55.0,49.0,26.0,100.0,91.0,82.0,...,10.0,5.0,1.0,18.0,9.0,36.0,1.170,8.0,Rain,158.0
14,2006-01-15,32.0,24.0,16.0,25.0,12.0,-1.0,92.0,62.0,32.0,...,10.0,6.0,0.0,31.0,13.0,39.0,0.120,5.0,Fog-Snow,298.0
15,2006-01-16,32.0,24.0,16.0,9.0,5.0,1.0,54.0,44.0,33.0,...,10.0,10.0,10.0,16.0,8.0,24.0,0.000,0.0,,279.0
16,2006-01-17,44.0,35.0,26.0,39.0,21.0,8.0,82.0,59.0,35.0,...,10.0,9.0,2.0,14.0,6.0,20.0,0.160,5.0,Rain,67.0
17,2006-01-18,58.0,47.0,36.0,55.0,43.0,19.0,93.0,69.0,44.0,...,10.0,6.0,2.0,28.0,12.0,41.0,0.590,7.0,Rain,217.0
18,2006-01-19,47.0,41.0,34.0,27.0,21.0,18.0,56.0,47.0,37.0,...,10.0,10.0,10.0,17.0,8.0,23.0,0.000,0.0,,244.0
19,2006-01-20,61.0,52.0,42.0,36.0,32.0,28.0,62.0,49.0,36.0,...,10.0,10.0,10.0,16.0,8.0,23.0,0.000,0.0,,233.0
20,2006-01-21,63.0,51.0,38.0,42.0,32.0,18.0,61.0,53.0,44.0,...,10.0,10.0,10.0,26.0,10.0,39.0,0.000,2.0,,263.0
21,2006-01-22,43.0,38.0,33.0,26.0,16.0,11.0,52.0,40.0,27.0,...,10.0,10.0,10.0,15.0,7.0,23.0,0.000,1.0,,49.0
22,2006-01-23,40.0,38.0,35.0,38.0,35.0,28.0,92.0,76.0,59.0,...,10.0,7.0,2.0,14.0,4.0,17.0,0.680,7.0,Rain-Snow,51.0
23,2006-01-24,46.0,41.0,35.0,30.0,26.0,15.0,76.0,54.0,31.0,...,10.0,10.0,10.0,14.0,7.0,18.0,0.000,1.0,,185.0
24,2006-01-25,42.0,38.0,34.0,32.0,26.0,18.0,82.0,65.0,47.0,...,10.0,10.0,10.0,22.0,10.0,32.0,0.000,4.0,,266.0
25,2006-01-26,35.0,31.0,26.0,19.0,14.0,10.0,56.0,47.0,38.0,...,10.0,10.0,10.0,21.0,14.0,30.0,0.000,1.0,,292.0
26,2006-01-27,43.0,34.0,24.0,15.0,10.0,4.0,60.0,40.0,19.0,...,10.0,10.0,10.0,16.0,8.0,22.0,0.000,0.0,,274.0
27,2006-01-28,58.0,48.0,37.0,27.0,20.0,14.0,40.0,33.0,26.0,...,10.0,10.0,10.0,13.0,6.0,21.0,0.000,0.0,,243.0
28,2006-01-29,53.0,49.0,44.0,49.0,39.0,26.0,93.0,66.0,38.0,...,10.0,8.0,2.0,13.0,5.0,20.0,0.140,5.0,Rain,169.0
29,2006-01-30,64.0,53.0,41.0,48.0,43.0,39.0,96.0,70.0,43.0,...,10.0,6.0,2.0,20.0,8.0,28.0,0.010,4.0,,64.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3257,2014-12-02,43.0,39.0,35.0,40.0,30.0,17.0,89.0,67.0,44.0,...,10.0,8.0,2.0,17.0,9.0,26.0,0.080,7.0,Rain,70.0
3258,2014-12-03,46.0,44.0,41.0,43.0,38.0,24.0,92.0,73.0,53.0,...,10.0,6.0,2.0,16.0,8.0,26.0,0.060,7.0,Rain,276.0
3259,2014-12-04,45.0,41.0,37.0,24.0,21.0,17.0,59.0,48.0,36.0,...,10.0,10.0,10.0,13.0,6.0,19.0,0.000,0.0,,304.0
3260,2014-12-05,44.0,39.0,34.0,41.0,33.0,19.0,89.0,69.0,48.0,...,10.0,6.0,1.0,17.0,6.0,21.0,0.510,6.0,Rain,50.0
3261,2014-12-06,50.0,45.0,39.0,47.0,42.0,36.0,96.0,88.0,80.0,...,8.0,3.0,1.0,17.0,4.0,30.0,1.220,8.0,Rain,36.0
3262,2014-12-07,42.0,36.0,30.0,35.0,18.0,0.0,92.0,62.0,32.0,...,10.0,10.0,10.0,25.0,12.0,40.0,0.040,1.0,Rain,28.0
3263,2014-12-08,37.0,31.0,24.0,30.0,17.0,-1.0,75.0,51.0,27.0,...,10.0,10.0,10.0,20.0,12.0,29.0,0.000,6.0,,60.0
3264,2014-12-09,42.0,39.0,36.0,38.0,36.0,30.0,92.0,81.0,70.0,...,10.0,5.0,1.0,22.0,10.0,32.0,2.540,8.0,Rain,36.0
3265,2014-12-10,40.0,36.0,32.0,36.0,31.0,23.0,89.0,74.0,59.0,...,10.0,6.0,1.0,16.0,8.0,24.0,0.080,8.0,Rain-Snow,295.0
3266,2014-12-11,38.0,35.0,31.0,26.0,23.0,20.0,75.0,62.0,48.0,...,10.0,9.0,2.0,17.0,8.0,25.0,0.010,7.0,Snow,276.0
3267,2014-12-12,38.0,35.0,32.0,23.0,21.0,19.0,61.0,57.0,52.0,...,10.0,10.0,10.0,15.0,8.0,25.0,0.000,6.0,,303.0
3268,2014-12-13,44.0,39.0,34.0,28.0,25.0,21.0,64.0,54.0,43.0,...,10.0,10.0,10.0,16.0,9.0,28.0,0.000,2.0,,307.0
3269,2014-12-14,46.0,42.0,38.0,29.0,29.0,28.0,70.0,60.0,49.0,...,10.0,10.0,10.0,13.0,6.0,20.0,0.000,4.0,,306.0
3270,2014-12-15,48.0,43.0,37.0,34.0,29.0,28.0,70.0,58.0,46.0,...,10.0,10.0,10.0,8.0,3.0,12.0,0.000,0.0,,333.0
3271,2014-12-16,49.0,44.0,38.0,43.0,39.0,32.0,86.0,76.0,65.0,...,10.0,6.0,2.0,12.0,4.0,14.0,0.200,7.0,Rain,75.0
3272,2014-12-17,54.0,48.0,42.0,43.0,39.0,26.0,92.0,73.0,53.0,...,10.0,7.0,2.0,16.0,6.0,26.0,0.020,7.0,Rain,294.0
3273,2014-12-18,42.0,40.0,37.0,25.0,23.0,21.0,59.0,52.0,45.0,...,10.0,10.0,10.0,16.0,9.0,28.0,0.000,6.0,,293.0
3274,2014-12-19,38.0,35.0,31.0,25.0,21.0,19.0,63.0,56.0,48.0,...,10.0,10.0,10.0,14.0,7.0,24.0,0.000,5.0,,307.0
3275,2014-12-20,33.0,32.0,30.0,21.0,19.0,18.0,63.0,57.0,51.0,...,10.0,10.0,10.0,12.0,5.0,15.0,0.000,8.0,,10.0
3276,2014-12-21,36.0,34.0,31.0,29.0,25.0,21.0,82.0,73.0,63.0,...,10.0,9.0,6.0,9.0,5.0,13.0,0.001,8.0,Snow,338.0
3277,2014-12-22,44.0,40.0,35.0,42.0,35.0,29.0,89.0,82.0,75.0,...,10.0,8.0,5.0,12.0,6.0,16.0,0.040,8.0,Rain,59.0
3278,2014-12-23,46.0,45.0,43.0,44.0,42.0,41.0,96.0,91.0,86.0,...,9.0,3.0,2.0,17.0,8.0,26.0,0.160,8.0,Rain,67.0
3279,2014-12-24,58.0,51.0,44.0,57.0,47.0,43.0,100.0,96.0,92.0,...,7.0,3.0,1.0,12.0,6.0,17.0,0.800,8.0,Rain,86.0
3280,2014-12-25,62.0,53.0,44.0,60.0,40.0,27.0,100.0,69.0,38.0,...,10.0,8.0,2.0,20.0,10.0,32.0,0.090,5.0,Rain,279.0
3281,2014-12-26,50.0,45.0,40.0,29.0,28.0,27.0,64.0,53.0,42.0,...,10.0,10.0,10.0,13.0,6.0,18.0,0.000,0.0,,272.0
3282,2014-12-27,55.0,50.0,44.0,35.0,31.0,29.0,53.0,47.0,41.0,...,10.0,10.0,10.0,14.0,4.0,25.0,0.000,0.0,,257.0
3283,2014-12-28,54.0,49.0,43.0,43.0,37.0,26.0,92.0,73.0,53.0,...,10.0,9.0,2.0,15.0,6.0,22.0,0.100,5.0,Rain,264.0
3284,2014-12-29,44.0,39.0,34.0,25.0,19.0,15.0,53.0,42.0,31.0,...,10.0,10.0,10.0,15.0,5.0,25.0,0.000,0.0,,308.0
3285,2014-12-30,34.0,31.0,28.0,17.0,13.0,8.0,58.0,47.0,36.0,...,10.0,10.0,10.0,10.0,4.0,17.0,0.000,2.0,,5.0
3286,2014-12-31,32.0,30.0,27.0,12.0,8.0,5.0,55.0,43.0,30.0,...,10.0,10.0,10.0,14.0,6.0,21.0,0.000,2.0,,275.0

In [55]:
# can use pd.to_datetime to convert a column to a datetime
date_str = nyc.EST.astype(str)
pd.to_datetime(date_str)

0      2006-01-01
1      2006-01-02
2      2006-01-03
3      2006-01-04
4      2006-01-05
5      2006-01-06
6      2006-01-07
7      2006-01-08
8      2006-01-09
9      2006-01-10
10     2006-01-11
11     2006-01-12
12     2006-01-13
13     2006-01-14
14     2006-01-15
15     2006-01-16
16     2006-01-17
17     2006-01-18
18     2006-01-19
19     2006-01-20
20     2006-01-21
21     2006-01-22
22     2006-01-23
23     2006-01-24
24     2006-01-25
25     2006-01-26
26     2006-01-27
27     2006-01-28
28     2006-01-29
29     2006-01-30
          ...
3257   2014-12-02
3258   2014-12-03
3259   2014-12-04
3260   2014-12-05
3261   2014-12-06
3262   2014-12-07
3263   2014-12-08
3264   2014-12-09
3265   2014-12-10
3266   2014-12-11
3267   2014-12-12
3268   2014-12-13
3269   2014-12-14
3270   2014-12-15
3271   2014-12-16
3272   2014-12-17
3273   2014-12-18
3274   2014-12-19
3275   2014-12-20
3276   2014-12-21
3277   2014-12-22
3278   2014-12-23
3279   2014-12-24
3280   2014-12-25
3281   2014-12-26
3282   2014-12-27
3283   2014-12-28
3284   2014-12-29
3285   2014-12-30
3286   2014-12-31
Name: EST, Length: 3287, dtype: datetime64[ns]

## Tweak Data Assignment
With the nino dataset:
* Replace the periods and spaces in the column names with underscores
* The temperatures are stored as Celsius. Create a new column, ``air_temp_F``, using Fahrenheit
  (Tf = Tc*9/5 + 32)
* The wind speed is in meters per second. Create new columns,  adding ``_mph``, that uses miles per hour ( 1 MPS = 2.237 MPH )
* Convert the ``date`` column to a date type.
* Drop the obs column

In [56]:
[x.rstrip('_') for x in nino.columns]

['obs',
 'year',
 'month',
 'day',
 'date',
 'latitude',
 'longitude',
 'zon.winds',
 'mer.winds',
 'humidity',
 'air temp.',
 's.s.temp.']

In [57]:
nino.columns=[x.strip() for x in nino.columns ]
nino.columns=[x.replace(' ','_') for x in nino.columns ]
nino.columns=[x.replace('.','_') for x in nino.columns ]
nino.head()

,obs,year,month,day,date,latitude,longitude,zon_winds,mer_winds,humidity,air_temp_,s_s_temp_
0,1,80,3,7,1980-03-07,-0.02,-109.46,-6.8,0.7,NaN,26.14,26.24
1,2,80,3,8,1980-03-08,-0.02,-109.46,-4.9,1.1,NaN,25.66,25.97
2,3,80,3,9,1980-03-09,-0.02,-109.46,-4.5,2.2,NaN,25.69,25.28
3,4,80,3,10,1980-03-10,-0.02,-109.46,-3.8,1.9,NaN,25.57,24.31
4,5,80,3,11,1980-03-11,-0.02,-109.46,-4.2,1.5,NaN,25.30,23.19

In [58]:
def transform_celcius_to_fahrenheit(series):
    return series*(9/5)+32
nino.air_temp_=transform_celcius_to_fahrenheit(nino.air_temp_)
nino.s_s_temp_=transform_celcius_to_fahrenheit(nino.s_s_temp_)

nino.head()

,obs,year,month,day,date,latitude,longitude,zon_winds,mer_winds,humidity,air_temp_,s_s_temp_
0,1,80,3,7,1980-03-07,-0.02,-109.46,-6.8,0.7,NaN,79.052,79.232
1,2,80,3,8,1980-03-08,-0.02,-109.46,-4.9,1.1,NaN,78.188,78.746
2,3,80,3,9,1980-03-09,-0.02,-109.46,-4.5,2.2,NaN,78.242,77.504
3,4,80,3,10,1980-03-10,-0.02,-109.46,-3.8,1.9,NaN,78.026,75.758
4,5,80,3,11,1980-03-11,-0.02,-109.46,-4.2,1.5,NaN,77.540,73.742

In [59]:
def transform_mps_mph(series):
    return series*2.237

nino['zon_winds_mph']=transform_mps_mph(nino.zon_winds)
nino['mer_winds_mph']=transform_mps_mph(nino.mer_winds)

In [60]:
date_str = nino.date.astype(str)
pd.to_datetime(date_str)

0        1980-03-07
1        1980-03-08
2        1980-03-09
3        1980-03-10
4        1980-03-11
5        1980-03-12
6        1980-03-13
7        1980-03-14
8        1980-03-15
9        1980-03-16
10       1980-03-17
11       1980-03-18
12       1980-03-19
13       1980-03-20
14       1980-03-21
15       1980-03-22
16       1980-03-23
17       1980-03-24
18       1980-03-25
19       1980-03-26
20       1980-03-27
21       1980-03-28
22       1980-03-29
23       1980-08-11
24       1980-08-12
25       1980-08-13
26       1980-08-14
27       1980-08-15
28       1980-08-16
29       1980-08-17
            ...
178050   1998-05-17
178051   1998-05-18
178052   1998-05-19
178053   1998-05-20
178054   1998-05-21
178055   1998-05-22
178056   1998-05-23
178057   1998-05-24
178058   1998-05-25
178059   1998-05-26
178060   1998-05-27
178061   1998-05-28
178062   1998-05-29
178063   1998-05-30
178064   1998-05-31
178065   1998-06-01
178066   1998-06-02
178067   1998-06-03
178068   1998-06-04
178069   1998-06-05
178070   1998-06-06
178071   1998-06-07
178072   1998-06-08
178073   1998-06-09
178074   1998-06-10
178075   1998-06-11
178076   1998-06-12
178077   1998-06-13
178078   1998-06-14
178079   1998-06-15
Name: date, Length: 178080, dtype: datetime64[ns]

In [61]:
nino=nino.drop(['obs'],axis=1)

In [62]:
nino.head()

,year,month,day,date,latitude,longitude,zon_winds,mer_winds,humidity,air_temp_,s_s_temp_,zon_winds_mph,mer_winds_mph
0,80,3,7,1980-03-07,-0.02,-109.46,-6.8,0.7,NaN,79.052,79.232,-15.2116,1.5659
1,80,3,8,1980-03-08,-0.02,-109.46,-4.9,1.1,NaN,78.188,78.746,-10.9613,2.4607
2,80,3,9,1980-03-09,-0.02,-109.46,-4.5,2.2,NaN,78.242,77.504,-10.0665,4.9214
3,80,3,10,1980-03-10,-0.02,-109.46,-3.8,1.9,NaN,78.026,75.758,-8.5006,4.2503
4,80,3,11,1980-03-11,-0.02,-109.46,-4.2,1.5,NaN,77.540,73.742,-9.3954,3.3555